-- Question 3
CREATE OR REPLACE VIEW VAptLibre AS
    SELECT
        LOGEMENTS.FK_NO_IMMEUBLE,
        LOGEMENTS.NO_LOGEMENT,
        LOGEMENTS.LOYER,
        LOGEMENTS.NB_CHAMBRES,
        IMMEUBLES.NB_LOGEMENTS,
        IMMEUBLES.ADRESSE
    FROM LOGEMENTS
    LEFT JOIN IMMEUBLES ON LOGEMENTS.FK_NO_IMMEUBLE = IMMEUBLES.NO_IMMEUBLE
    WHERE
        LOGEMENTS.FK_OCC_CODE = 'L' AND -- L pour Libre
        LOGEMENTS.LOYER < 1750.00 AND
        LOGEMENTS.NB_CHAMBRES = 3 AND
        IMMEUBLES.NB_LOGEMENTS > 25
    ;

-- Question 4

CREATE OR REPLACE VIEW Vreparation
AS
    SELECT
        LOGEMENTS.NO_LOGEMENT,
        TAUX_METIERS.DESCRIPTION_METIER,
        ENTRETIENS.ENT_DATE
    FROM ENTRETIENS
    LEFT JOIN IMMEUBLES ON
        ENTRETIENS.FK_IMM_NO_IMMEUBLE = IMMEUBLES.NO_IMMEUBLE
    LEFT JOIN LOGEMENTS ON
        LOGEMENTS.FK_NO_IMMEUBLE = ENTRETIENS.FK_IMM_NO_IMMEUBLE AND
        LOGEMENTS.NO_LOGEMENT = ENTRETIENS.FK_LOG_NO_LOGEMENT
    LEFT JOIN EMPLOYES ON
        ENTRETIENS.FK_EMP_EMP_NOM = EMPLOYES.EMP_NOM
    LEFT JOIN TAUX_METIERS ON
        EMPLOYES.FK_TAUX_CODE_METIER = TAUX_METIERS.CODE_METIER
    WHERE
        LOGEMENTS.FOYER = 'O' AND
        LOGEMENTS.SALLE_A_DINER = 'N' AND
        IMMEUBLES.FK_VIL_NOM_VILLE IN ('Boucherville', 'St-Bruno') AND
        (ENTRETIENS.ENT_DATE BETWEEN date '2023-06-01' AND date '2023-06-25')
    ;

-- Question 5

CREATE OR REPLACE VIEW VPetitApt
AS
SELECT
    IMMEUBLES.ADRESSE,
    IMMEUBLES.CONCIERGERIE,
    (SELECT
        COUNT(*)
    FROM LOGEMENTS
    WHERE LOGEMENTS.FK_NO_IMMEUBLE = IMMEUBLES.NO_IMMEUBLE AND
    LOGEMENTS.NB_CHAMBRES > 2) as COUNT_NB_CHAMBRES_SUPERSIEUR_2
FROM IMMEUBLES
WHERE (
    SELECT
        COUNT(*)
    FROM LOGEMENTS
    WHERE LOGEMENTS.FK_NO_IMMEUBLE = IMMEUBLES.NO_IMMEUBLE AND
    LOGEMENTS.NB_CHAMBRES > 2
) = 0
;

-- Question 6

CREATE OR REPLACE VIEW VConcierges
    AS
    SELECT
        LOCATAIRES.LOC_NOM
        -- LOGEMENTS.FK_OCC_CODE,
        -- LOGEMENTS.MEUBLE,
        -- LOGEMENTS.FOYER,
        -- IMMEUBLES.FK_VIL_NOM_VILLE
    FROM LOGEMENTS
    RIGHT JOIN LOCATAIRES ON
        LOCATAIRES.FK_LOG_NO_IMMEUBLE = LOGEMENTS.FK_NO_IMMEUBLE AND
        LOCATAIRES.FK_LOG_NO_LOGEMENT = LOGEMENTS.NO_LOGEMENT
    LEFT JOIN IMMEUBLES ON
        IMMEUBLES.NO_IMMEUBLE = LOGEMENTS.FK_NO_IMMEUBLE
    WHERE
        LOGEMENTS.FK_OCC_CODE = 'C' AND
        LOGEMENTS.MEUBLE = 'S' AND
        LOGEMENTS.FOYER = 'O' AND
        IMMEUBLES.FK_VIL_NOM_VILLE = 'Longeuil'
    ORDER BY LOCATAIRES.LOC_NOM DESC
    ;

-- Question 7
CREATE OR REPLACE FUNCTION f_loyer(P_NO_IMMEUBLE in NUMBER)
    RETURN NUMBER
IS
    revenu_total_loyer_juin NUMBER;
    revenu_logement_concierge_juin NUMBER;

    depense_total_loyer_juin NUMBER;
BEGIN
    SELECT
        SUM(LOGEMENTS.LOYER) INTO revenu_total_loyer_juin
    FROM LOGEMENTS
    RIGHT JOIN LOCATAIRES ON
        LOCATAIRES.FK_LOG_NO_IMMEUBLE = LOGEMENTS.FK_NO_IMMEUBLE AND
        LOCATAIRES.FK_LOG_NO_LOGEMENT = LOGEMENTS.NO_LOGEMENT

    WHERE locataires.date_entree <= to_date('01-06-' || to_char(sysdate, 'YYYY'), 'DD-MM-YYYY') AND
        locataires.date_fin_bail >= to_date('30-06-' || to_char(sysdate, 'YYYY'), 'DD-MM-YYYY') AND
        LOGEMENTS.FK_NO_IMMEUBLE = P_NO_IMMEUBLE AND
        LOGEMENTS.FK_OCC_CODE = 'R'
    ;

    SELECT
        SUM(LOGEMENTS.LOYER / 2) INTO revenu_logement_concierge_juin
    FROM LOGEMENTS
    RIGHT JOIN LOCATAIRES ON
        LOCATAIRES.FK_LOG_NO_IMMEUBLE = LOGEMENTS.FK_NO_IMMEUBLE AND
        LOCATAIRES.FK_LOG_NO_LOGEMENT = LOGEMENTS.NO_LOGEMENT

    WHERE locataires.date_entree <= to_date('01-06-' || to_char(sysdate, 'YYYY'), 'DD-MM-YYYY') AND
        locataires.date_fin_bail >= to_date('30-06-' || to_char(sysdate, 'YYYY'), 'DD-MM-YYYY') AND
        LOGEMENTS.FK_NO_IMMEUBLE = P_NO_IMMEUBLE AND
        LOGEMENTS.FK_OCC_CODE = 'C'
    ;
    revenu_total_loyer_juin := revenu_total_loyer_juin + revenu_logement_concierge_juin;

    IF revenu_total_loyer_juin is null THEN
        RETURN 0;
    END IF;


    RETURN revenu_total_loyer_juin;

END;
/

CREATE OR REPLACE VIEW V_LOYER
AS
    SELECT
        IMMEUBLES.NO_IMMEUBLE,
        IMMEUBLES.ADRESSE,
        IMMEUBLES.CONCIERGERIE,
        f_loyer(IMMEUBLES.NO_IMMEUBLE) as REVENU_LOYER
    FROM IMMEUBLES
;
/

-- Question 8
CREATE OR REPLACE PROCEDURE sp_archive (P_NO_IMMEUBLE IN NUMBER)
IS
BEGIN
    INSERT INTO ARCHIVES
    SELECT
        IMMEUBLES.NO_IMMEUBLE AS FK_NO_IMMEUBLE,
        IMMEUBLES.ANNEE_EN_COURS AS ANNEE,
        IMMEUBLES.EVALUATION,
        PRIX_ACHAT * VILLES.TAUX_TAXES as TAXES,
        HYPOTHEQUE AS FRAIS_HYPOTHEQUE,
        IMMEUBLES.CONCIERGERIE,
        IMMEUBLES.ASSURANCE AS ASSURANCES,
        IMMEUBLES.ENTRETIEN,
        f_loyer(IMMEUBLES.NO_IMMEUBLE) as REVENU_LOYER
    FROM IMMEUBLES
    LEFT JOIN VILLES ON
        VILLES.NOM_VILLE = IMMEUBLES.FK_VIL_NOM_VILLE
    WHERE NO_IMMEUBLE = P_NO_IMMEUBLE;
END;
/

CALL SP_ARCHIVE(1297);
/

-- Question 9
CREATE OR REPLACE PROCEDURE SP_AUGMENTATION(P_TYPE_CHAUFFAGE IN VARCHAR2(1), P_POURCENTAGE IN NUMBER)
IS
BEGIN
    UPDATE LOGEMENTS
        SET LOYER = LOYER * (1 + P_POURCENTAGE / 100.0)
    WHERE LOGEMENTS.FK_CHAUFFAGE = P_TYPE_CHAUFFAGE;
END;

CALL SP_AUGMENTATION('G', 7);
